# Generated by Django 3.1 on 2020-08-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=60)),
                ('nextcourse', models.IntegerField()),
                ('previouscourse', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonname', models.CharField(max_length=60)),
                ('nextlesson', models.IntegerField()),
                ('previouslesson', models.IntegerField()),
                ('approvalscore', models.IntegerField()),
                ('couseid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.TextField()),
                ('question', models.TextField()),
                ('score', models.IntegerField()),
                ('lessonid', models.IntegerField()),
            ],
        ),
    ]
