# Generated by Django 3.1 on 2020-08-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapi', '0003_auto_20200813_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='coursename',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='lession',
            old_name='lessonname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lession',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
