# Generated by Django 3.1 on 2020-08-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapi', '0004_auto_20200813_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='nextcourse',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='previouscourse',
            field=models.IntegerField(default=0),
        ),
    ]
