# Generated by Django 3.1 on 2020-08-14 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapi', '0006_auto_20200813_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='nextcourse',
            new_name='nextcourseid',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='previouscourse',
            new_name='previouscourseid',
        ),
        migrations.RenameField(
            model_name='lession',
            old_name='nextlesson',
            new_name='nextlessonid',
        ),
        migrations.RenameField(
            model_name='lession',
            old_name='previouslesson',
            new_name='previouslessonid',
        ),
    ]
