# Generated by Django 3.1 on 2020-08-14 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapi', '0007_auto_20200813_1918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lession',
            new_name='Lesson',
        ),
    ]
