# Generated by Django 3.1 on 2020-08-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapi', '0008_auto_20200813_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='questiontype',
            field=models.IntegerField(default=0),
        ),
    ]
